### ISSUE TITLE
PEM certificate key load fails on ruby 2.4.1

### ISSUE THREAD

**Issue by jmartin-r7** [rapid7/metasploit-aggregator#8]
When creating a cable with an associated SSL certificate the PEM private key passed fails to parse when executing on ruby 2.4.1.

```
/ruby-2.4.1@metasploit-aggregator/gems/grpc-1.2.2-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:46:in `check_status': 2:OpenSSL::OpenSSLError: password must be at least 4 bytes (GRPC::Unknown)
	from /Users/jmartin/.rvm/gems/ruby-2.4.1@metasploit-aggregator/gems/grpc-1.2.2-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:178:in `attach_status_results_and_complete_call'
	from /Users/jmartin/.rvm/gems/ruby-2.4.1@metasploit-aggregator/gems/grpc-1.2.2-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:340:in `request_response'
	from /Users/jmartin/.rvm/gems/ruby-2.4.1@metasploit-aggregator/gems/grpc-1.2.2-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
	from /Users/jmartin/.rvm/gems/ruby-2.4.1@metasploit-aggregator/gems/grpc-1.2.2-universal-darwin/src/ruby/lib/grpc/generic/service.rb:185:in `block (3 levels) in rpc_stub_class'
	from /Users/jmartin/rapid7/src/r7-source/metasploit/metasploit-aggregator/ruby/lib/metasploit/aggregator.rb:143:in `add_cable'
	from ./test_ssl.rb:17:in `<main>'
```
### Reproduction steps
start `metasploit-aggregator`

```
openssl req -new -newkey rsa:2048 -nodes -x509 -subj '/CN=localhost' -days 365 -keyout server.key -out server.crt && cat server.key server.crt > server.pem
```

Test code
```
#!/usr/bin/env ruby

require 'bundler/setup'
require 'metasploit/aggregator'
require 'metasploit/aggregator/cable'
require 'metasploit/aggregator/logger'

admin_host = '127.0.0.1'
admin_port = 2447
cert_file = './server.pem'
cert_string = File.new(cert_file).read

host = admin_host
port = 4444

client = Metasploit::Aggregator::ServerProxy.new(admin_host, admin_port)
client.add_cable(Metasploit::Aggregator::Cable::HTTPS, host, port, cert_string)
```

**Comment by jmartin-r7** [comment]
Fixed in 821d9afe97c1ebbd514987282dc1ccd6cec8806f
